language: julia
julia:
- 1.0
os:
- linux
- osx
notifications:
  email: false
after_success:
- julia -e 'cd(Pkg.dir("BeaData")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
env:
  secure: fIfFPjL1X93uqJfjmRh/FH3zFSzK2GrOM0QQ+K6v9JqK26va1zodUVUt4NBrPwQCWGivKVRDr68A76zuxsmdgDLTaFqIB0dK4eOXBLHe0D8v1bZd+9r0zarwbUCobOsol5Q4JYV4P6LijVwLi0ZSTHJ7FT6gO5e5d4YZhwL/P+LqME5Gy8W3VvX4t6qGadvxG3mfRdFkd3eZT96AqHqmNu7fyAxyKnbRr5emPoAeig8JBihp8jju0vTlvLtEgSFr3OhHiIMUyphTydxNn89hf4iabaRUqgnGTKMDDzbjnyp1EPsnpoy55wFCogppbWJoonX5XQbiGMH3xYLOFlBXmKBLc4iNGXCz1XCdL8FjyeNFIV2Nu4rD/M67nbgkmUvz5+vOpJy3+jytW+jKBWM3wcDQAmV6i2aCOWcibiT3fLqNN0Ncbe9ZmiwaKlk5g0pSBB5DkaUEIlTLjf7aMaMIanoH0oDDzsStIf0dete6MdRGHKfeVi6PsgL2NZjyUw+OQ4TwX6Hf3GbhHYKHXwVmeGjsNzNlsHpeRO1Jq4SWc3QLB7MK+Nb67GGZhvtUHQJHSN3Ux9XDtMIaagJtboO8Wu4SbEGBE+vh73XwKAJcg3jYLKWHvceNdqEwwOLznmn/TRXwZg62btfHFkrkG0TqjYEeMSt72mKAzjKsM/Abwgg=
